spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:database/schema/54ysy.sql
    data:
      - classpath:database/data/RelationshipInfo.sql
      - classpath:database/data/UserInfo.sql
#      - classpath:database/data/ImageInfo.sql
    separator: ;;
    initialization-mode: always
  mvc:
    converters:
      preferred-json-mapper: gson

server:
  port: 80


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

qiniu:
  accessKey:  eCnHA6rDVdbhQ6KX-qaDltge0vKDDd26-MiWn2K2
  secretKey:  LVvD1P8Df-x0zwawqH70v0kPT30Ix1wCYwiLtvtN
  defaultAvatar:  avatar/default.jpg